services:

  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB:?Variable not set}

  prestart:
    image: "${DOCKER_IMAGE}:${TAG:-latest}"
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: ["bash", "scripts/prestart.sh"]
    env_file:
      - .env
    environment:
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY:?Variable not set}
      - ROOT_USER_EMAIL=${ROOT_USER_EMAIL:?Variable not set}
      - ROOT_USER_PASSWORD=${ROOT_USER_PASSWORD:?Variable not set}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT:?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB:?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER:?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Variable not set}

  backend:
    image: "${DOCKER_IMAGE}:${TAG:-latest}"
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
      prestart:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY:?Variable not set}
      - ROOT_USER_EMAIL=${ROOT_USER_EMAIL:?Variable not set}
      - ROOT_USER_PASSWORD=${ROOT_USER_PASSWORD:?Variable not set}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT:?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB:?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER:?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Variable not set}
    ports:
      - "8000:8000"

volumes:
  db_data: 